apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-oauth-port
spec:
  ingress:
  - ports:
    - port: 4180
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress