{{ if .Values.keycloak }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-keycloak
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.keycloak.client_id }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.keycloak.client_secret }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ randAlphaNum 24 | quote }}

{{ end }}