apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: basic
  namespace: {{ .Values.user.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "code-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: basic
  apiGroup: ""
